apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: kargo-demo
  namespace: kargo-demo
spec:
  webhookReceivers: 
    - name: gitea-wh-receiver
      gitea:
        secretRef:
          name: gitea-wh-secret
    - name: gitlab-wh-receiver
      gitlab:
        secretRef:
          name: gitlab-wh-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-wh-secret
  namespace: kargo-demo
stringData:
  secret: not-so-secret-gitea-token
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-wh-secret
  namespace: kargo-demo
stringData:
  secret: not-so-secret-gitlab-token
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: my-test-warehouse
  namespace: kargo-demo
spec:
  # Intentionally setting a really high internal interval to avoid
  # conflating warehouse refreshes triggered by the webhooks
  # with regular reconciliation refreshes.
  interval: 30m
  subscriptions:
  - git:
      repoURL: git@gitlab.com:farisakuity/test-kargo-5611.git
      branch: main
      strictSemvers: false
  - git:
      repoURL: git@gitea.com:farisakuity/test-kargo-5611.git
      branch: main
      strictSemvers: false