apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: gitea
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: gitea
  namespace: gitea
spec:
  webhookReceivers: 
    - name: gitea-wh-receiver
      gitea:
        secretRef:
          name: gitea-wh-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-wh-secret
  namespace: gitea
stringData:
  secret: not-so-secret-token
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: my-warehouse
  namespace: gitea
spec:
  # Intentionally setting a really high internal interval to avoid
  # conflating warehouse refreshes triggered by the webhooks
  # with regular reconciliation refreshes. Same thing for disabling strict semver.
  interval: 30m
  subscriptions:
  - git:
      repoURL: https://gitea.com/farisakuity/test-kargo-5611.git
      branch: main
      strictSemvers: false
      includePaths:
        - "gitea/**"