apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: gitlab
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: gitlab
  namespace: gitlab
spec:
  webhookReceivers: 
    - name: gitlab-wh-receiver
      gitlab:
        secretRef:
          name: gitlab-wh-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-wh-secret
  namespace: gitlab
stringData:
  secret: not-so-secret-token
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: my-gitlab-warehouse
  namespace: gitlab
spec:
  # Intentionally setting a really high internal interval to avoid
  # conflating warehouse refreshes triggered by the webhooks
  # with regular reconciliation refreshes. Same thing for disabling strict semver.
  interval: 30m
  subscriptions:
  - git:
      repoURL: https://gitlab.com/farisakuity/test-kargo-5611.git
      branch: main
      strictSemvers: false
      includePaths:
        - "gitlab/**"